### PR TITLE
WebDAM Plugin Refactoring

### PR DESCRIPTION
**Pull request by jamesmehorter**
Hi WebDAM :)

We’ve refactored the plugin extensively using the WordPress Coding Standards to bring it more in line with best practices for WordPress plugins. We’ve also incorporated a few additional features which should be useful for most all users/enterprises. Those features include: 
- WebDAM API integration (for selecting assets and using the API)
- An updated Settings > WebDAM page
- Optionally sideload selected assets into the WordPress media library (during which the API is hit to pull in asset metadata). 
- Asset multi-select support as a default.

**A few notes:**
- The plugin now works seamlessly on standalone single-site WordPress, WordPress multi-site, and WordPress VIP (via `wpcom_vip_load_plugin()`)
- The .htaccess directives mentioned in the README for cross-domain comms are no longer needed as those rules are added 'the WordPress way' via the allowed_http_origins filter. See `includes/class-asset-chooser.php:64:allowed_http_origins()`
- We migrated history from our repo where this work was done. As such there are a few automated commits from Jenkins, and some debugging commits. Please ignore these.
- The bulk of our work on this was done in a JIRA ticket _'PMCVIP-831'_ and as such many commits are prepended with that name. Please ignore these. Going forward we'll work off this new repo and won't include stuff like that.
- We don't have much resources to continue working on this _(yet)_. If any of these changes require further edits we'd recommend merging this PR and creating Issues for each item—keep it moving forward (if they are small edits we can do them in this PR). If you ping me in those Issues I'll do my best to get approval to work on them and submit PR's for those items.

cc @adamholisky @mintindeed

### CODE REVIEW

**Comment by jamesmehorter** [comment]
Hey @DMinton :) Just wanted to see how this review is going? Do you need anything else from us? Any feedback on the PR yet? Ping me with any questions/concerns/etc..

**Comment by DMinton** [comment]
@jamesmehorter We are still trying to figure out our process for a PR to our public repo and it has been slow going with a major release this coming weekend.

The only concern that has been brought up to me is allowing the users to login using the API key. This is likely to be an issue for some of our users since this allows all permissions to be bypassed and the user could potentially see assets they are not allowed to see. Ideally what we would like to see if for an option to prompt users to log in (old way) and an option to just use the API key like you guys have implemented. How much extra time/effort/work would that be on your side?

**Comment by jamesmehorter** [comment]
Hey @DMinton, that makes sense. We can definitely make that change here in this PR. I'll work on that this afternoon and update this PR/let you know when it's up :)

**Comment by DMinton** [comment]
@jamesmehorter Sounds good! Once we get the PR properly QAed I will also get back to you. Hopefully this week and at the worst case it will be early next week. Should calm down a bit after this weekend.

**Comment by jamesmehorter** [comment]
Hey @DMinton, just pushed a refactoring which makes using the API optional, and using the API for logging into the Asset Chooser also optional. Now, when you first install the plugin it defaults to 'session' mode so the user is prompted to log into WebDAM only when choosing assets. If they enable the API, authorize it, and select 'Use the API to sign into the Asset Chooser' 'oauth' mode is used and users are signed into the Asset Chooser using the API. This allows a few different options for users:
- Keep it simple and users are asked to sign in when selecting assets
- Or, automatically use one single login for all users via the API
- Or, require users to sign in, AND maintain the API for sideloading assets using a master account

screen shot 2016-05-19 at 12 53 37 pm

Feel free to start reviewing—everything is working smoothly for me, though per our email and the https issue I still have a little testing to complete (inserting assets). Once that issue is ironed out I'll complete testing.

**Comment by DMinton** [comment]
@jamesmehorter Now that the UTF8 madness is over I should be able to get some QA time on this. I will also look into your https issue. I followed it along and I believe I may have found the problem but did not have time to fix and test it. I will hopefully have it fixed for you today but our next release is on Thursday, so it will not be out until then at best.

**Comment by DMinton** [comment]
@jamesmehorter I just tried uploading the newest version of the plugin and I get an error like below when I try to activate the plugin

`Fatal error: Call to undefined function Webdam\webdam_get_settings() in /home/ubuntu/wordpress/wp-content/plugins/Webdam-Wordpress-Asset-Chooser/includes/class-api.php on line 92`

When I followed the error, it looks like it was happening because `webdam-asset-chooser.php` is trying to include class-api.php which requires helpers.php. I thought I may have checked out the incorrect commit but got the error on both f885c52 and 9a3345e.

**Comment by jamesmehorter** [comment]
Hmmm taking a look..

**Comment by jamesmehorter** [comment]
Hey @DMinton, good catch! I've pushed out some commits to correct that issue. Have a look now..

**Comment by jamesmehorter** [comment]
Hey @DMinton, just checking in to see how this review is coming along?

**Pull request merged**
